name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
        enable-AzPSSession: true

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'

    - name: Run Tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx" || true

    - uses: dorny/test-reporter@v1
      with:
        name: Pipeline Tests
        path: "**/test-results.trx" 
        reporter: dotnet-trx
        fail-on-error: true